### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by effigies** [ArcanaFramework/fileformats#58]
Given the focus on typing in Pydra 0.23, it would be nice to get it to type-check cleanly, which would be helped by the types of fileformats being available.

I don't consider this blocking, just opening an issue for the sake of having the plan on the record.

**Comment by tclose** [comment]
Hi @effigies, sorry, I'm not sure I know what you mean? Where do they need to be available?

**Comment by effigies** [comment]
Right now, `fileformats` types are not available to `mypy` or `pyright` running on pydra's source. This is due to a lack of a `py.typed` file in your package root. I checked, and neither runs cleanly on this repo, either.

Right now, the way to do type-checking in pydra would be to add a `type: ignore[import]` comment to fileformats imports, which would make all of your types effectively `Any`.

So I was just curious if there was a plan to type check this library and then add a `py.typed` so that its types could be inspected by downstream libraries.

**Comment by tclose** [comment]
Ah, I didn't realise that you needed to do anything special to a package get mypy to inspect it.

I had a quick go at fixing up those typing errors but it looks like I might need to set aside a day or two to get through them all. I have opened #61 to do this

**Comment by tclose** [comment]
This has been implemented in v0.12.0
