### ISSUE TITLE
Adding Authorship

### ISSUE THREAD

**Issue by tclose** [ArcanaFramework/fileformats#60]
@effigies, I was wondering whether you would like to be considered an author of fileformats or not (see AUTHORS file). `FileSet.copy` uses the logic that you outlined when we were discussing this in the context of Pydra.

I have also just incorporated the CIFS/mount logic that was in Pydra into fileformats as I have found that I need it when using fileformats outside of Pydra.

No worries if you'd rather not put your name to it, but just thought I would offer/mention it.

**Comment by effigies** [comment]
Hi Tom. Thanks for the offer, but I don't feel the need to be considered an author here.

(That said, if for some reason it is helpful to you to have an additional author listed on your tools, I would be fine with it.)

**Comment by tclose** [comment]
No worries, just thought I would check. I will open up a PR to strip out the `MountIdentifier` code from Pydra in favour of the copy in fileformats in a bit
